### ISSUE TITLE
Unhandled rejection TypeError: result.data.reverse is not a function

### ISSUE THREAD

**Issue by vanita5** [vanita5/birdknife#25]
Occured while executing `/again <screenname>`. Maybe due to a slow internet connection.

`Unhandled rejection TypeError: result.data.reverse is not a function
    at /usr/lib/node_modules/birdknife/libs/TwitterAPI.js:130:29
    at tryCatcher (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/birdknife/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by canonex** [comment]
I get the same message, firefox on Linux, since few days:

```
Error: data.reverse is not a function
refreshGlobalChanges</<@http://localhost:8384/syncthing/core/syncthingController.js:629:29
$http/promise.success/<@http://localhost:8384/vendor/angular/angular.js:7597:11
wrappedCallback@http://localhost:8384/vendor/angular/angular.js:10968:81
wrappedCallback@http://localhost:8384/vendor/angular/angular.js:10968:81
then/<@http://localhost:8384/vendor/angular/angular.js:11054:26
$eval@http://localhost:8384/vendor/angular/angular.js:11974:28
$digest@http://localhost:8384/vendor/angular/angular.js:11800:31
$apply@http://localhost:8384/vendor/angular/angular.js:12080:24
done@http://localhost:8384/vendor/angular/angular.js:7862:45
completeRequest@http://localhost:8384/vendor/angular/angular.js:8045:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:8384/vendor/angular/angular.js:8001:11
    method http://localhost:8384/syncthing/development/logbar.js:11
    Angular 11
```
A warn appears on a yellow top bar and on a red popup (Errore di Connessione)

Thank you,
Riccardo
